- name: Déployer l'application depuis un artefact GitLab
  hosts: front
  become: yes

  tasks:
    - name: Installer les dépendances nécessaires
      apt:
        name:
          - curl
          - unzip
          - nginx
        state: present

    - name: Créer le répertoire de destination s'il n'existe pas
      file:
        path: "/var/www/html"
        state: directory

    - name: Télécharger l'artefact depuis GitLab
      get_url:
        url: "http://10.5.0.5:81/api/v4/projects/1/jobs/artifacts/main/download?job=build_angular"
        dest: "/tmp/artifact.zip"

    - name: Extraire l'artefact
      unarchive:
        src: "/tmp/artifact.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Extraire l'artefact
      unarchive:
        src: "/tmp/front.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Déplacer les fichiers dans le répertoire de destination
      shell: "mv /tmp/dist/front/* /var/www/html"

    - name: S'assurer que les permissions sont correctes
      file:
        path: "/var/www/html"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Redémarrer le service web (par exemple nginx)
      service:
        name: nginx
        state: restarted
