- name: Déployer l'application depuis un artefact GitLab
  hosts: back
  become: yes
  vars:
    gitlab_url: "http://10.5.0.5:81/api/v4/projects/2/jobs/artifacts/main/download?job=build_application"
    dest_dir: "/var/www/html"
    artifact_name: "back.zip"

  tasks:
    - name: Mise à jour de la liste des paquets
      apt:
        update_cache: yes
    - name: Installer les dépendances nécessaires
      apt:
        name:
          - curl
          - unzip
          - nginx
          - php
          - php-fpm
          - php-mysql
        state: present

    - name: Créer le répertoire de destination s'il n'existe pas
      file:
        path: "{{ dest_dir }}"
        state: directory

    - name: Télécharger l'artefact depuis GitLab
      get_url:
        url: "{{ gitlab_url }}"
        dest: "/tmp/artifact.zip"

    - name: Extraire l'artefact
      unarchive:
        src: "/tmp/artifact.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Extraire l'artefact
      unarchive:
        src: "/tmp/{{ artifact_name }}"
        dest: "{{ dest_dir }}"
        remote_src: yes

    - name: S'assurer que les permissions sont correctes
      file:
        path: "{{ dest_dir }}"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Redémarrage du service nginx automatiquement
      command: systemctl enable nginx

    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted

    - name: Redémarrer php-fpm
      service:
        name: php8.2-fpm
        state: restarted
