- name: Déploiement de la base de données MySQL
  hosts: db
  become: yes

  tasks:
    - name: Mise à jour de la liste des paquets
      apt:
        update_cache: yes

    - name: Installation de MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Install ansible python3 mysql dependency
      apt:
        name: python3-mysqldb
        state: latest

    - name: Configuration de MariaDB
      template:
        src: .my.cnf
        dest: /etc/mysql/my.cnf
      notify: Redémarrer MariaDB

  handlers:
    - name: Redémarrer MariaDB
      service:
        name: mariadb
        state: restarted
